[package]
name = "ipdl"
version = "0.1.0"
authors = ["Tristan Bourvon <tristanbourvon@gmail.com>", "Andrew McCreight <continuation@gmail.com>"]
license = "MPL-2.0"

[dependencies]
pipdl = { git = "https://github.com/tbourvon/pipdl-rs" }

[lib]
name = "ipdl"
path = "src/lib.rs"
