[package]
name = "ipdl-rs"
version = "0.1.0"
authors = ["Tristan Bourvon <tristanbourvon@gmail.com>", "Nika Layzell <nika@thelayzells.com>", "Andrew McCreight <continuation@gmail.com>"]
license = "MPL-2.0"

[dependencies]
